- title: Shirts?  Gimme a break.  We got some damn shirts!
  caption: So Best just generally kicks ass in the T-Shirt and sticker arena.
  icon: computer

- title: Super Sticky
  caption: So Best stickers will stick like nobody's business.
  icon: workers-group

- title: Cool guys
  caption: The guys behind So Best are incredibly funny and charming.
  icon: graduate

- title: You know what's So Best?
  caption: Badass Shirts and Stickers
  icon: unique-idea

- title: You know what sucks?
  caption: |-
    Not having anything that is So Best
  icon: business-man

- title: It's like this
  caption: |-
    You have boring windows on your car and a boring torso to boot.  You need So Best Stickers and Shirts
  icon: code
